modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="mekaweapons"
version="1.0"
displayName="Mekanism: Weapons"
authors="oMeranha"
description='''Weapons for Mekanism.'''
[[dependencies.mekaweapons]]
	modId="forge"
	mandatory=true
	versionRange="[47,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.mekaweapons]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.20.1,1.21)"
	ordering="NONE"
	side="BOTH"
[[dependencies.mekaweapons]]
	modId="mekanism"
	mandatory=true
	versionRange="10.4.0.14"
	ordering="AFTER"
	side="BOTH"
[[dependencies.mekaweapons]]
	modId="curios"
	mandatory=true
	versionRange="5.3.5+1.20.1"
	ordering="AFTER"
	side="BOTH"
