modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="mekaweapons"
version="1.0"
displayName="Mekanism Weapons"
authors="oMeranha"
description='''Weapons for Mekanism.'''
[[dependencies.mekaweapons]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version}"
    side="BOTH"
[[dependencies.mekaweapons]]
    modId="forge"
    mandatory=true
    versionRange="43.1.3"
    side="BOTH"
[[dependencies.mekaweapons]]
    modId="mekanism"
    mandatory=true
    versionRange="10.3.3"
    side="BOTH"
[[dependencies.mekaweapons]]
    modId="curios"
    mandatory=true
    versionRange="[1.18.2-5.0.7.1,)"
    ordering="AFTER"
